spring:
  application:
    name: portfolio-cms
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:keycloak_server_url}/realms/Portfolio/protocol/openid-connect/certs

  datasource:
    url: ${DATABASE_URL:db_url}
    username: ${DATABASE_USER_NAME:db_username}
    password: ${DATABASE_PASSWORD:db_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com:
      portfolio: DEBUG
      logging:
    org:
      keycloak: DEBUG
#      springframework:
#        web:
#          client: DEBUG
#      apache:
#        http: DEBUG
#      okhttp3: DEBUG

springdoc:
  swagger-ui:
    oauth:
      client-id: ${KEYCLOAK_CLIENT_ID:keycloak_client_id}
      client-secret: ${KEYCLOAK_CLIENT_SECRET:keycloak_client_secret}
    persist-authorization: true

fileUploader:
  path: /

s3:
  accessKey: ${S3_ACCESS_KEY:s3_access_key}
  region: ${S3_REGION:s3_region}
  secretKey: ${S3_SECRET_KEY:s3_secret_key}
  bucketName: ${S3_BUCKET_NAME:s3_bucket_name}

uploadServiceType: s3

keycloak:
  realm: ${KEYCLOAK_REALM:keycloak_realm}
  server-url: ${KEYCLOAK_SERVER_URL:keycloak_server_url}
  client-id: ${KEYCLOAK_CLIENT_ID:keycloak_client_id}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:keycloak_client_secret}

server:
  port: 8085

microservice:
  portfolio-account-url: http://localhost:8084
  portfolio-cms-url: http://localhost:8085
  portfolio-gateway-url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: cms-service
  tracing:
    sampling:
      probability: 1.0
