spring:
  application:
    name: portfolio
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/Portfolio/protocol/openid-connect/certs

  datasource:
    url: ${DATABASE_URL:db_url}
    username: ${DATABASE_USER_NAME:db_username}
    password: ${DATABASE_PASSWORD:db_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com:
      portfolio: DEBUG

springdoc:
  swagger-ui:
    oauth:
      client-id: portfolio
      client-secret: smdkaXIUHYEY5NPwsVn5eJtG3I2ENUN5

fileUploader:
  path: /

s3:
  accessKey: ${S3_ACCESS_KEY:s3_access_key}
  region: ${S3_REGION:s3_region}
  secretKey: ${S3_SECRET_KEY:s3_secret_key}
  bucketName: ${S3_BUCKET_NAME:s3_bucket_name}

uploadServiceType: s3

jwt:
  secretKey: ${JWT_SECRET_KEY:jwt_secret}
  refreshKey: ${JWT_REFRESH_SECRET_KEY:jwt_refresh_secret}
  expiry_time: ${JWT_EXPIRY_TIME:1800000}
  refresh_expiry_time: ${JWT_REFRESH_EXPIRY_TIME:1800000}

keycloak:
  realm: ${KEYCLOAK_REALM:keycloak_realm}
  server-url: ${KEYCLOAK_SERVER_URL:keycloak_server_url}
  client-id: ${KEYCLOAK_CLIENT_ID:keycloak_client_id}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:keycloak_client_secret}
